#! /usr/bin/env python

import sys
import socket

def main(args):
    # store the command line arguments
    hostname = args[1]
    port = args[2]
    
    # create the socket object
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    # get the host ip address
    try:
        ip = socket.gethostbyname(hostname)
        print ip
    except socket.gaierror:
        print "Could not resolve host"
        return 0
    
    # connect to the host
    s.connect((ip, int(port)))
    
    # send a request and store the reply
    request = 'GET / HTTP/1.0\r\n\r\n'
    s.sendall(request)
    reply = s.recv(4096)
    print reply
    
    reply = s.recv(4096)
    print reply

if __name__ == '__main__':
    main(sys.argv)