#! /usr/bin/env python

import sys
import socket

def main(args):
    # store the command line arguments
    hostname = args[0]
    port = args[1]
    
    # create the socket object
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    # get the host ip address
    try:
        ip = socket.gethostbyname(hostname)
    except socket.gaierror:
        print "Could not resolve host"
        return 0
    
    # connect to the host
    s.connect((ip, port))
    
    # send a request and store the reply
    request = 'GET / HTTP1.1'
    s.send(request)
    reply = s.recv(4096)
    
    print reply

if __name__ == '__main__':
    main(sys.argv)